services:
  order-book-db:
    image: mariadb:latest
    command: --innodb-use-native-aio=0
    container_name: order-book-db
    restart: always
    tty: true
    volumes:
      - type: volume
        source: order-book-db
        target: /var/lib/mysql
    environment:
      - MYSQL_DATABASE=order-book-db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - order-book-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024MB
    ports:
      - 3306:3306

  order-book:
    restart: always
    image: on-luan/order-book
    build:
      context: .
    container_name: order-book
    ports:
      - 8081:80
    networks:
      - order-book-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024MB

volumes:
  order-book-db:

networks:
  order-book-network:
    driver: bridge